apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-bgpk
    appstudio.openshift.io/component: test-component-lqjo
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-component-lqjo
  namespace: build-e2e-hacbs-cywj
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: test-component-lqjo
status:
  configuration:
    generatedName: ""
