apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-lqjo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-lqjo
    app.kubernetes.io/part-of: test-app-bgpk
  name: test-component-lqjo
  namespace: build-e2e-hacbs-cywj
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-lqjo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-lqjo
    spec:
      containers:
      - image: quay.io/mkovarik/test-images:fd3d37ceef974fd49101edc2bd2e64f5
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
